export const typography = {
  fontFamilies: {
    regular: 'PlusJakartaSans_400Regular',
    medium: 'PlusJakartaSans_500Medium',
    semibold: 'PlusJakartaSans_600SemiBold',
    bold: 'PlusJakartaSans_700Bold',
    extrabold: 'PlusJakartaSans_800ExtraBold',
  },
  fontSizes: {
    displayHero: 46,
    displayLg: 36,
    displayMd: 28,
    displaySm: 22,
    hero: 34,
    headingLg: 26,
    headingMd: 20,
    headingSm: 17,
    bodyLg: 16,
    body: 14,
    caption: 12,
    micro: 10,
  },
  fontWeights: {
    regular: '400' as const,
    medium: '500' as const,
    semibold: '600' as const,
    bold: '700' as const,
    extrabold: '800' as const,
  },
  lineHeights: {
    displayHero: 52,
    displayLg: 42,
    displayMd: 34,
    displaySm: 28,
    hero: 42,
    headingLg: 34,
    headingMd: 26,
    headingSm: 22,
    bodyLg: 24,
    body: 20,
    caption: 16,
    micro: 14,
  },
  letterSpacing: {
    tight: -1.2,
    snug: -0.6,
    normal: 0,
    wide: 0.5,
    wider: 1.0,
  },
};

